module.exports = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_ROOMMESSAGES_REQUEST: 'FETCH_ROOMMESSAGES_REQUEST',
  FETCH_ROOMMESSAGES_SUCCESS: 'FETCH_ROOMMESSAGES_SUCCESS',
  FETCH_ROOMMESSAGES_FAILURE: 'FETCH_USERS_FAILURE'
}
